# The name of the keyboard (max 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="Corne Cherry v3"

# Enable split keyboard support
CONFIG_ZMK_SPLIT=y

# Enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# -----( USB Support )----- #
# Enable ZMK as a USB keyboard
CONFIG_ZMK_USB=n

# Enable USB Boot protocol support
# CONFIG_ZMK_USB_BOOT=y


# -----( Bluetooth Support )----- #
# Enable ZMK as a Bluetooth keyboard
CONFIG_ZMK_BLE=y

# Clears all bond information from the keyboard on startup
# CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
