{ config, pkgs, lib, unstable, ... }:
{

  options = {
    hyprland.enable = lib.mkEnableOption "enable hyprland settings";
  };

  config = lib.mkIf config.hyprland.enable {

    # needed packages for hyprland
    home.packages = with pkgs; [
      blueman
      cava
      fastfetch
      jq
      kitty
      krabby
      nautilus
      playerctl
      python3
      rofi-wayland
      swaynotificationcenter
      waybar
      wlogout
    ];

    # pokemon terminal in bashrc
    programs.bash.initExtra = ''
      ${pkgs.krabby}/bin/krabby random | {
        read POKEMON_NAME
        export POKEMON_NAME
        ${pkgs.fastfetch}/bin/fastfetch --logo /dev/stdin \
          --structure "Title:Separator:Custom:Kernel:Uptime:Packages:Shell:Display:CPU:LocalIp" \
          --title-key "Host" \
          --custom-key "Pokemon" \
          --custom-format "$POKEMON_NAME"
      };
    '';

# settings
wayland.windowManager.hyprland = {
  enable = true;
  settings = {
    # Remove autogenerated warning
    autogenerated = 0;

    # Monitors
    monitor = ",preferred,auto,auto";

    # Programs
    "$terminal" = "kitty";
    "$fileManager" = "nautilus";
    "$menu" = "wofi --show drun";

    # Autostart
    exec-once = [
      "waybar"
      "$terminal"
      # "nm-applet &"
      # "waybar & hyprpaper & firefox"
    ];

    # Environment variables
    env = [
      "XCURSOR_SIZE,24"
      "HYPRCURSOR_SIZE,24"
    ];

    # Permissions (commented out)
    # ecosystem = {
    #   enforce_permissions = 1;
    # };

    # permission = [
    #   "/usr/(bin|local/bin)/grim, screencopy, allow"
    #   "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow"  
    #   "/usr/(bin|local/bin)/hyprpm, plugin, allow"
    # ];

    # General settings
    general = {
      gaps_in = 5;
      gaps_out = 20;
      border_size = 2;
      "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
      "col.inactive_border" = "rgba(595959aa)";
      resize_on_border = false;
      allow_tearing = false;
      layout = "dwindle";
    };

    # Decoration
    decoration = {
      rounding = 10;
      rounding_power = 2;
      active_opacity = 1.0;
      inactive_opacity = 1.0;
      
      shadow = {
        enabled = true;
        range = 4;
        render_power = 3;
        color = "rgba(1a1a1aee)";
      };
      
      blur = {
        enabled = true;
        size = 3;
        passes = 1;
        vibrancy = 0.1696;
      };
    };

    # Animations
    animations = {
      enabled = true;
      
      bezier = [
        "easeOutQuint,0.23,1,0.32,1"
        "easeInOutCubic,0.65,0.05,0.36,1"
        "linear,0,0,1,1"
        "almostLinear,0.5,0.5,0.75,1.0"
        "quick,0.15,0,0.1,1"
      ];
      
      animation = [
        "global, 1, 10, default"
        "border, 1, 5.39, easeOutQuint"
        "windows, 1, 4.79, easeOutQuint"
        "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
        "windowsOut, 1, 1.49, linear, popin 87%"
        "fadeIn, 1, 1.73, almostLinear"
        "fadeOut, 1, 1.46, almostLinear"
        "fade, 1, 3.03, quick"
        "layers, 1, 3.81, easeOutQuint"
        "layersIn, 1, 4, easeOutQuint, fade"
        "layersOut, 1, 1.5, linear, fade"
        "fadeLayersIn, 1, 1.79, almostLinear"
        "fadeLayersOut, 1, 1.39, almostLinear"
        "workspaces, 1, 1.94, almostLinear, fade"
        "workspacesIn, 1, 1.21, almostLinear, fade"
        "workspacesOut, 1, 1.94, almostLinear, fade"
      ];
    };

    # Smart gaps workspace rules (commented out)  
    # workspace = [
    #   "w[tv1], gapsout:0, gapsin:0"
    #   "f[1], gapsout:0, gapsin:0"
    # ];

    # Smart gaps window rules (commented out)
    # windowrule = [
    #   "bordersize 0, floating:0, onworkspace:w[tv1]"
    #   "rounding 0, floating:0, onworkspace:w[tv1]"
    #   "bordersize 0, floating:0, onworkspace:f[1]"
    #   "rounding 0, floating:0, onworkspace:f[1]"
    # ];

    # Dwindle layout
    dwindle = {
      pseudotile = true;
      preserve_split = true;
    };

    # Master layout
    master = {
      new_status = "master";
    };

    # Misc
    misc = {
      force_default_wallpaper = -1;
      disable_hyprland_logo = false;
    };

    # Input
    input = {
      kb_layout = "us,de";
      kb_variant = "";
      kb_model = "";
      kb_options = "grp:win_space_toggle,caps:escape";
      kb_rules = "";
      follow_mouse = 1;
      sensitivity = 0;
      
      touchpad = {
        natural_scroll = false;
      };
    };

    # Gestures
    gestures = {
      workspace_swipe = false;
    };

    # Per-device config
    device = {
      name = "epic-mouse-v1";
      sensitivity = -0.5;
    };

    # Main modifier key
    "$mainMod" = "SUPER";

    # Keybinds
    bind = [
      "$mainMod, Q, exec, $terminal"
      "$mainMod, C, killactive"
      "$mainMod, M, exit"
      "$mainMod, E, exec, $fileManager"
      "$mainMod, V, togglefloating"
      "$mainMod, R, exec, $menu"
      "$mainMod, P, pseudo"
      "$mainMod, J, togglesplit"

      # Move focus with arrow keys
      "$mainMod, left, movefocus, l"
      "$mainMod, right, movefocus, r"
      "$mainMod, up, movefocus, u"
      "$mainMod, down, movefocus, d"

      # Switch workspaces
      "$mainMod, 1, workspace, 1"
      "$mainMod, 2, workspace, 2"
      "$mainMod, 3, workspace, 3"
      "$mainMod, 4, workspace, 4"
      "$mainMod, 5, workspace, 5"
      "$mainMod, 6, workspace, 6"
      "$mainMod, 7, workspace, 7"
      "$mainMod, 8, workspace, 8"
      "$mainMod, 9, workspace, 9"
      "$mainMod, 0, workspace, 10"

      # Move window to workspace
      "$mainMod SHIFT, 1, movetoworkspace, 1"
      "$mainMod SHIFT, 2, movetoworkspace, 2"
      "$mainMod SHIFT, 3, movetoworkspace, 3"
      "$mainMod SHIFT, 4, movetoworkspace, 4"
      "$mainMod SHIFT, 5, movetoworkspace, 5"
      "$mainMod SHIFT, 6, movetoworkspace, 6"
      "$mainMod SHIFT, 7, movetoworkspace, 7"
      "$mainMod SHIFT, 8, movetoworkspace, 8"
      "$mainMod SHIFT, 9, movetoworkspace, 9"
      "$mainMod SHIFT, 0, movetoworkspace, 10"

      # Special workspace (scratchpad)
      "$mainMod, S, togglespecialworkspace, magic"
      "$mainMod SHIFT, S, movetoworkspace, special:magic"

      # Scroll through workspaces
      "$mainMod, mouse_down, workspace, e+1"
      "$mainMod, mouse_up, workspace, e-1"
    ];

    # Volume and brightness keys
    bindel = [
      ",XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
      ",XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+"
      ",XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-"
    ];

    # Media keys
    bindl = [
      ", XF86AudioNext, exec, playerctl next"
      ", XF86AudioPause, exec, playerctl play-pause"
      ", XF86AudioPlay, exec, playerctl play-pause"
      ", XF86AudioPrev, exec, playerctl previous"
    ];

    # Mouse binds
    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];

    # Window rules
    windowrule = [
      # "float,class:^(kitty)$,title:^(kitty)$"
      "suppressevent maximize, class:.*"
      "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
    ];
  };
};

    # copy local config files for waybar
    home.file = {
      ".config/waybar".source = ../config/waybar;
      ".config/hypr/scripts".source = ../config/waybar/hypr/scripts;
      ".config/hypr/UserScripts".source = ../config/waybar/hypr/UserScripts;
      ".config/hypr/UserConfigs".source = ../config/waybar/hypr/UserConfigs;
    };

  };

}